#Global stuff
fidelius:
  sessionTimeout: 900000
  sessionTimeoutPad: 10000

server:
  contextPath: /api/fidelius

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: container

---
#Local Profile
spring:
  profiles: local

---

#Container Profile
spring:
  profiles: container

